name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  publish_rocks:
    runs-on: ubuntu-latest
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        path: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    steps:
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release-please-outputs
      - run: echo "PACKAGE=$(echo "${{ matrix.path }}" | awk -F/ '{ print $2 }' )" | tee -a $GITHUB_ENV
      - run: echo "VERSION=$(jq -r --arg A "${{ matrix.path }}--version" '.[$A]' outputs)" | tee -a $GITHUB_ENV
      - run: echo "TAG_NAME=$(jq -r --arg A "${{ matrix.path }}--tag_name" '.[$A]' outputs)" | tee -a $GITHUB_ENV
      - run: envsubst < ${{ matrix.path }}/rockspec > ${PACKAGE}-${VERSION}-1.rockspec
      - run: luarocks pack ${PACKAGE}-${VERSION}-1.rockspec
      - uses: actions/upload-artifact@v3
        with:
          name: rocks
          path: ${{ env.PACKAGE }}-${{ env.VERSION }}*
      - uses: ptonini/gha-upload-release@main
        with:
          file: ${{ env.PACKAGE }}-${{ env.VERSION }}*
          file_glob: true
          repo_token: ${{ github.token }}
          tag: ${{ env.TAG_NAME }}
  update_repository:
    runs-on: ubuntu-latest
    needs:
      - publish_rocks
    steps:
      - uses: leafo/gh-actions-lua@v9
      - uses: leafo/gh-actions-luarocks@v4
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: rocks
          path: gh-pages
      - run: luarocks-admin make-manifest --local-tree ./gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages